"use client";
import { useRef, useState } from "react";
import { Upload } from "lucide-react";

export function AdminUploadPanel({ galleryId, images }: { galleryId: string; images: Array<{ id: string; original_filename: string }> }) {
  const [mode, setMode] = useState<"preview"|"final">("preview"); const [progress, setProgress] = useState(0); const [results, setResults] = useState<Array<{ name: string; ok: boolean; error?: string }>>([]); const formRef = useRef<HTMLFormElement>(null);
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); data.set("mode", mode); setResults([]); setProgress(0); const xhr = new XMLHttpRequest(); xhr.open("POST", `/api/admin/galleries/${galleryId}/upload`); xhr.upload.onprogress = (e) => e.lengthComputable && setProgress(Math.round(e.loaded / e.total * 100)); xhr.onload = () => { try { const body = JSON.parse(xhr.responseText); setResults(body.results || [{ name: "Upload", ok: false, error: body.error }]); if (xhr.status >= 200 && xhr.status < 300) formRef.current?.reset(); } catch { setResults([{ name: "Upload", ok: false, error: "Unexpected upload response" }]); } }; xhr.onerror = () => setResults([{ name: "Upload", ok: false, error: "Network upload failed" }]); xhr.send(data); }
  return <section className="admin-panel"><div className="admin-panel-head"><div><p className="portal-kicker">Private storage</p><h2>Upload photographs</h2></div><div className="segmented"><button className={mode === "preview" ? "active" : ""} onClick={() => setMode("preview")}>Watermarked previews</button><button className={mode === "final" ? "active" : ""} onClick={() => setMode("final")}>Final file</button></div></div><form onSubmit={submit} ref={formRef} className="upload-form">{mode === "final" && <label>Pair final to preview<select name="imageId" required><option value="">Choose preview</option>{images.map((image) => <option key={image.id} value={image.id}>{image.original_filename}</option>)}</select></label>}<label className="drop-field"><Upload /><span>{mode === "preview" ? "Choose JPEG, PNG or WebP previews" : "Choose the matching high-resolution final"}</span><input name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple={mode === "preview"} required /></label><button className="portal-primary">Upload securely</button>{progress > 0 && progress < 100 && <div className="upload-progress"><span style={{ width: `${progress}%` }} /><small>{progress}% uploaded</small></div>}</form><div aria-live="polite" className="upload-results">{results.map((result) => <p key={result.name} className={result.ok ? "success" : "error"}>{result.name}: {result.ok ? "uploaded" : result.error}</p>)}</div></section>;
}
