import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, Download } from "lucide-react";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/AdminNav";
import { AdminUploadPanel } from "@/components/admin/AdminUploadPanel";
import { archiveGallery, assignGalleryMember, removeGalleryMember, updateGallery, updateGalleryImage } from "@/app/actions/admin";
import { requireAdmin } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { displayStatus } from "@/lib/gallery/status";

export const dynamic = "force-dynamic";
const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0,16) : "";

export default async function GalleryAdmin({ params }: { params: Promise<{ galleryId: string }> }) {
  await requireAdmin(); const galleryId = (await params).galleryId; const admin = createAdminClient();
  const { data: gallery } = await admin.from("galleries").select("*,gallery_members(user_id,profiles(full_name,email))").eq("id", galleryId).single(); if (!gallery) notFound();
  const [{ data: images = [] }, { data: selections = [] }, { data: comments = [] }, { data: activity = [] }, { data: clients = [] }] = await Promise.all([
    admin.from("gallery_images").select("*").eq("gallery_id",galleryId).order("sort_order"), admin.from("image_selections").select("*").eq("gallery_id",galleryId), admin.from("image_comments").select("*").eq("gallery_id",galleryId).order("created_at",{ascending:false}), admin.from("gallery_activity").select("*").eq("gallery_id",galleryId).order("created_at",{ascending:false}).limit(50), admin.from("profiles").select("id,full_name,email").eq("role","client").eq("is_active",true).order("full_name")
  ]);
  const previews = await Promise.all((images || []).map(async (image) => ({ ...image, url: (await admin.storage.from("gallery-previews").createSignedUrl(image.preview_path,300)).data?.signedUrl || "" })));
  const finalCount = (images || []).filter((image) => image.final_path).length; const assignedIds = new Set((gallery.gallery_members || []).map((m: { user_id: string }) => m.user_id));
  return <main className="admin-shell"><AdminNav /><header className="admin-subhead"><div><p className="portal-kicker">{displayStatus(gallery.workflow_status, gallery.expires_at)}</p><h1>{gallery.title}</h1></div><div className="admin-head-actions"><Link href={`/api/admin/galleries/${galleryId}/selections.csv`}><Download /> Export selections</Link><Link href={`/client/galleries/${galleryId}`}>Client view</Link></div></header>
    {gallery.payment_status === "paid" && !finalCount && <div className="workflow-banner danger"><AlertTriangle /><div><strong>Payment is marked paid but no final files exist.</strong><p>Downloads remain blocked until final files are paired and enabled.</p></div></div>}
    <section className="admin-summary"><div><span>{images?.length || 0}</span><p>Previews</p></div><div><span>{finalCount}</span><p>Finals paired</p></div><div><span>{selections?.filter((s) => s.status === "approved").length || 0}</span><p>Approvals</p></div><div><span>{comments?.length || 0}</span><p>Comments</p></div></section>
    <AdminUploadPanel galleryId={galleryId} images={(images || []).map((image) => ({ id:image.id, original_filename:image.original_filename }))} />
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="portal-kicker">Access</p><h2>Assigned clients</h2></div></div><div className="member-list">{(gallery.gallery_members || []).map((member: { user_id: string; profiles: { full_name: string; email: string } | null }) => <div key={member.user_id}><span><strong>{member.profiles?.full_name}</strong><small>{member.profiles?.email}</small></span><form action={removeGalleryMember}><input type="hidden" name="gallery_id" value={galleryId}/><input type="hidden" name="user_id" value={member.user_id}/><button>Remove</button></form></div>)}</div><form action={assignGalleryMember} className="inline-form"><input type="hidden" name="gallery_id" value={galleryId}/><select name="user_id" required><option value="">Add another client</option>{(clients || []).filter((c) => !assignedIds.has(c.id)).map((c) => <option key={c.id} value={c.id}>{c.full_name} — {c.email}</option>)}</select><button>Add client</button></form></section>
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="portal-kicker">Workflow and payment</p><h2>Gallery controls</h2></div></div><form action={updateGallery} className="admin-form wide"><input type="hidden" name="id" value={galleryId}/><div className="admin-form-row"><label>Workflow status<select name="workflow_status" defaultValue={gallery.workflow_status}>{["preview_available","awaiting_selection","editing","awaiting_payment","ready","archived"].map((v) => <option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label>Payment status<select name="payment_status" defaultValue={gallery.payment_status}>{["not_requested","awaiting_payment","paid","refunded"].map((v) => <option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label></div><div className="admin-form-row"><label>Amount due<input name="amount_due" type="number" step="0.01" min="0" defaultValue={gallery.amount_due || ""}/></label><label>Amount paid<input name="amount_paid" type="number" step="0.01" min="0" defaultValue={gallery.amount_paid || ""}/></label><label>Currency<input name="currency" maxLength={3} defaultValue={gallery.currency}/></label></div><div className="admin-form-row"><label>Payment reference<input name="payment_reference" defaultValue={gallery.payment_reference || ""}/></label><label>Secure payment URL<input name="payment_url" type="url" placeholder="https://" defaultValue={gallery.payment_url || ""}/></label></div><label>Payment notes<textarea name="payment_notes" defaultValue={gallery.payment_notes || ""}/></label><div className="admin-form-row"><label>Selection deadline<input name="selection_deadline" type="datetime-local" defaultValue={localDate(gallery.selection_deadline)}/></label><label>Expiry date<input name="expires_at" type="datetime-local" defaultValue={localDate(gallery.expires_at)}/></label></div><fieldset className="toggle-grid"><label><input type="checkbox" name="comments_enabled" defaultChecked={gallery.comments_enabled}/> Comments enabled</label><label><input type="checkbox" name="selections_enabled" defaultChecked={gallery.selections_enabled}/> Selections enabled</label><label><input type="checkbox" name="selections_locked" defaultChecked={gallery.selections_locked}/> Lock selections</label><label><input type="checkbox" name="downloads_enabled" defaultChecked={gallery.downloads_enabled}/> Downloads enabled</label></fieldset><button className="portal-primary">Save workflow and payment</button></form><form action={archiveGallery} className="archive-form"><input type="hidden" name="id" value={galleryId}/><input type="hidden" name="reactivate" value={String(gallery.workflow_status === "archived")}/><button>{gallery.workflow_status === "archived" ? "Reactivate gallery" : "Archive gallery"}</button></form></section>
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="portal-kicker">Photographs</p><h2>Preview and final pairing</h2></div></div><div className="admin-image-grid">{previews.map((image) => <article key={image.id}><div className="admin-thumb">{image.url && <Image src={image.url} alt={image.alt_text} fill sizes="240px"/>}<span>{image.final_path ? "Final paired" : "Preview only"}</span></div><form action={updateGalleryImage}><input type="hidden" name="gallery_id" value={galleryId}/><input type="hidden" name="image_id" value={image.id}/><label>Title<input name="title" defaultValue={image.title || ""}/></label><label>Alt text<input name="alt_text" required defaultValue={image.alt_text}/></label><label>Order<input name="sort_order" type="number" defaultValue={image.sort_order}/></label><label className="check-line"><input name="is_downloadable" type="checkbox" defaultChecked={image.is_downloadable}/> Enable this final</label><label className="check-line"><input name="set_cover" type="checkbox"/> Set as cover</label><button>Save image</button></form></article>)}</div></section>
    <section className="admin-two-col"><div className="admin-panel"><h2>Client comments</h2><div className="activity-list">{(comments || []).map((comment) => <article key={comment.id}><time>{new Date(comment.created_at).toLocaleString()}</time><p>{comment.comment}</p></article>)}{!comments?.length && <p className="muted">No client comments yet.</p>}</div></div><div className="admin-panel"><h2>Gallery activity</h2><div className="activity-list">{(activity || []).map((item) => <article key={item.id}><time>{new Date(item.created_at).toLocaleString()}</time><p>{item.event_type.replaceAll("_"," ")}</p></article>)}</div></div></section>
  </main>;
}
